apiVersion: v1
kind: ClusterRole
metadata:
  name: project-reader
rules:
- apiGroups: null
  attributeRestrictions: null
  resources:
  - projectrequests
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
