apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: web-secret
    namespace: python-web
  stringData: 
    text: Goodbye World
    alternate: Howdy World
- apiVersion: v1
  kind: Pod
  metadata:
    name: python-web-with-secret
  spec:
    containers:
    - image: jdob/python-web
      imagePullPolicy: Always
      name: python-web
      env:
      - name: TEXT
        valueFrom:
          secretKeyRef:
            name: web-secret
            key: text
      ports:
      - containerPort: 8080
        protocol: TCP
    restartPolicy: Always
