apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: python-web
    name: python-web-dc
  spec:
    replicas: 1
    selector:
      app: python-web
      deploymentconfig: python-web-dc
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          app: python-web
          deploymentconfig: python-web-dc
      spec:
        containers:
        - image: jdob/python-web
          imagePullPolicy: Always
          name: python-web
          env:
          - name: TEXT
            valueFrom:
              secretKeyRef:
                name: web-secret
                key: text     
          ports:
          - containerPort: 8080
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    test: false
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: python-web
    name: web-secret
  stringData: 
    text: Goodbye World
    alternate: Howdy World    
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: python-web
    name: python-web-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: python-web
      deploymentconfig: python-web-dc
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: python-web
    name: python-web-route
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: python-web-service
      weight: 100
    wildcardPolicy: None
