apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp-01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/openshift

