apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv01
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /pv/pv1
      server: 192.168.1.5
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv02
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /pv/pv2
      server: 192.168.1.5
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv03
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /pv/pv3
      server: 192.168.1.5
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv04
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /pv/pv4
      server: 192.168.1.5
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv05
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /pv/pv5
      server: 192.168.1.5

